# Dependencies

markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            KO Today
tagline:          'A Jekyll theme'
description:      'Welcome to the website that will change your life'
url:              http://hyde.getpoole.com
baseurl:          '/hyde/'

author:
  name:           'Shrinaath Narasimhan'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
